baseURL = 'https://blog.dais0n.net/'
title = 'dais0nNote'
theme = 'smol'
hasCJKLanguage = true
canonifyurls = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags/"
    weight = 3
  [[menu.footer]]
    name = "Github"
    url = "https://github.com/dais0n"
    weight = 1
  [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/dais0n_"
    weight = 2
